name: Build & Publish

on:
  push:
    tags:
      - "v*"

  # Ou manualmente pelo GitHub
  workflow_dispatch:

permissions:
  contents: write # Obrigat√≥rio para subir arquivos na Release

jobs:
  build-and-upload:
    name: Build on ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            name: Windows
          - os: macos-latest
            name: macOS ARM
          - os: macos-15-intel
            name: macOS Intel
          - os: ubuntu-latest
            name: Linux

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm fakeroot

      - name: Install Dependencies
        run: npm install

      - name: Compile (Make)
        run: npm run make

      - name: List Artifacts
        shell: bash
        run: |
          echo "Looking for files in out/make..."
          ls -R out/make || echo "Folder not found"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Ferramentas-Guru-${{ matrix.name }}
          path: |
            out/make/**/*.exe
            out/make/**/*.nupkg
            out/make/**/RELEASES
            out/make/**/*.zip
            out/make/**/*.dmg
            out/make/**/*.rpm
            out/make/**/*.deb
          retention-days: 30

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            out/make/**/*.exe
            out/make/**/*.nupkg
            out/make/**/RELEASES
            out/make/**/*.zip
            out/make/**/*.dmg
            out/make/**/*.rpm
            out/make/**/*.deb
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
